### ISSUE TITLE
Integrate Google Authentication 

### ISSUE THREAD

**Issue by adityyaa-10** [adityyaa-10/monthly-wrap#42]
In our current setup, the signup process is quite long and time taking as we speak, which is surely a bad user experience

![image](https://github.com/adityyaa-10/monthly-wrap/assets/103577578/98b38a29-78ef-4f76-b7c7-d8d04d71e284)

Task is to integrate Google and GitHub authentication in our website.

## Reference 

![image](https://github.com/adityyaa-10/monthly-wrap/assets/103577578/997bb354-a90a-47a9-84e8-44c230c324e6)

**Comment by adityyaa-10** [comment]
HI @Deb-cybe, can you explain the approach you are going to implement for this issue

**Comment by Deb-cybe** [comment]
First of all, take apologies for being inactive. The approach I was thinking to implement for the issue was using firebase for authentication.

**Comment by adityyaa-10** [comment]
@Deb-cybe I'll get back to you on this!

**Comment by adityyaa-10** [comment]
@Deb-cybe you can carry on with this issue! Good luck👍🏽
