### ISSUE TITLE
Improve User Interface for full blog page

### ISSUE THREAD

**Issue by adityyaa-10** [adityyaa-10/monthly-wrap#43]
### Currently. this is how a blog looks like when clicked on the read more button.

![image](https://github.com/adityyaa-10/monthly-wrap/assets/103577578/7052a57f-8b62-4396-b3fe-08cabc1c62a3)

The task is to update the user interface **USING TAILWIND CSS ONLY** to make it look more attractive

You can use icons for like and comment button.

**Comment by bharath090909** [comment]
@adityyaa-10 can I take up on this Task ?

**Comment by sayyedarib** [comment]
hey! can you please assign this to me?

**Comment by Kalp22** [comment]
I can take up the task i will use react js

**Comment by adityyaa-10** [comment]
I'll let @bharath090909 take this issue

@sayyedarib @Kalp22 you guys can have a brief look to the website and can suggest ui changes. All you have to do is raise an issue and propose the changes and I'll assign it to you guys.

Let me know if you guys face any difficulty.

**Comment by bharath090909** [comment]
@adityyaa-10 I have completed the task and raised a PR. Let me know if any changes required. Thanks for giving opportunity 😁.
