### ISSUE TITLE
Adding Tech Related Categories

### ISSUE THREAD

**Issue by adityyaa-10** [adityyaa-10/monthly-wrap#47]
![image](https://github.com/adityyaa-10/monthly-wrap/assets/103577578/007cf41c-4c44-4fcf-978f-64d170df2ded)

## Here in the categories dropdown, categories are to be added.

Just head towards BlogCreate.jsx file and add categories to choose from 

![image](https://github.com/adityyaa-10/monthly-wrap/assets/103577578/55b00fcc-53f2-488b-a6ab-696c697497cc)

**Comment by kiranrokkam09** [comment]
Hi @adityyaa-10 , I would like to take on this issue. Could you please assign it to me?

**Comment by adityyaa-10** [comment]
@kiranrokkam09 sure, don't forget to make a new branch

**Comment by kiranrokkam09** [comment]
Hey @adityyaa-10, are the categories below sufficient, or would you like me to add more?
![BlogCreate jsx - monthly-wrap - Visual Studio Code 06-10-2023 12_10_35 AM](https://github.com/adityyaa-10/monthly-wrap/assets/85286397/ecd89315-03b9-4097-9679-c60388985093)

**Comment by adityyaa-10** [comment]
@kiranrokkam09 LGTM!

**Comment by adityyaa-10** [comment]
@kiranrokkam09 Raise a pr and mention issue number.

**Comment by kiranrokkam09** [comment]
@adityyaa-10 ok

**Comment by kiranrokkam09** [comment]
@adityyaa-10 I've just raised a pull request for the issue #47
