### ISSUE TITLE
Create custom sidebar and Profile Dropdown

### ISSUE THREAD

**Issue by adityyaa-10** [adityyaa-10/monthly-wrap#50]
## Currently the sidebar is taken from flowbite library and profile dropdown is taken from headless ui library

![image](https://github.com/adityyaa-10/monthly-wrap/assets/103577578/12f2aac7-905d-4c07-8e72-f328711a2cec)

Task is to create our own sidebar and dropdown, keeping the design consistent as it is.

# Need ?

Using lesser dependencies would help in overall application performance.

**Comment by amrahs02** [comment]
Assign this to me. I want to work on this.

**Comment by adityyaa-10** [comment]
Cool @amrahs02 I'm assigning it  to you. Don't forget to make a separate branch, good luck!

**Comment by amrahs02** [comment]
Hey @adityyaa-10 I am getting some issues, can you give this to someone else?
